services:
  db:
    image: postgres:15
    container_name: bank_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: greenwealth_db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: greenwealth_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/greenwealth_db
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=dev_password
